name: Build, test, and push Docker image

on: pull_request

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jmk07g/grpc-demo-app-go
          tags: latest
          dockerfile: ./src/go/server/Dockerfile
